name: Test Action

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 23f1002296@ds.study.iitm.ac.in
        run: echo "Hello, world!"
