name: Simple Workflow

on:
  workflow_dispatch: # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 23f1002296@ds.study.iitm.ac.in
        run: echo "Hello, world!"
